global proc shelf_ProjectTools () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "FBXxporter" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "FBXxporter" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -imageOverlayLabel "xport" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "C:/Users/williamdelisle/Documents/maya/2019/scripts/fbxporterUI_Icon64.png" 
        -image1 "C:/Users/williamdelisle/Documents/maya/2019/scripts/fbxporterUI_Icon64.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "import fbxporterUI\nreload(fbxporterUI)" 
        -sourceType "python" 
        -doubleClickCommand "import fbxporterUI\nfbxporterUI.helpWindowUI()" 
        -commandRepeatable 1
        -flat 1
    ;

} 
