//Maya ASCII 2019 scene
//Name: Lyette_Walk.ma
//Last modified: Mon, Apr 13, 2020 09:11:23 PM
//Codeset: 1252
file -rdi 1 -ns "animRig_Lyette_GameReady_Modified" -rfn "animRig_Lyette_GameReady_ModifiedRN"
		 -op "v=0;" -typ "mayaAscii" "D:/Projects/Games/COVID/COVID/SourceFiles/Characters/MainCharacter/Rig/animRig_Lyette_GameReady_Modified.ma";
file -r -ns "animRig_Lyette_GameReady_Modified" -dr 1 -rfn "animRig_Lyette_GameReady_ModifiedRN"
		 -op "v=0;" -typ "mayaAscii" "D:/Projects/Games/COVID/COVID/SourceFiles/Characters/MainCharacter/Rig/animRig_Lyette_GameReady_Modified.ma";
requires maya "2019";
requires "mtoa" "3.1.2";
requires -nodeType "ilrOptionsNode" -nodeType "ilrUIOptionsNode" -nodeType "ilrBakeLayerManager"
		 -nodeType "ilrBakeLayer" "Turtle" "2019.0.0";
currentUnit -l centimeter -a degree -t ntsc;
fileInfo "application" "maya";
fileInfo "product" "Maya 2019";
fileInfo "version" "2019";
fileInfo "cutIdentifier" "201812112215-434d8d9c04";
fileInfo "osv" "Microsoft Windows 10 Technical Preview  (Build 18362)\n";
fileInfo "license" "student";
createNode transform -s -n "persp";
	rename -uid "99517373-48F5-96E5-3DD5-A6BD4E5AAB7A";
	setAttr ".v" no;
	setAttr ".t" -type "double3" -29.10790525750576 13.339155028978386 39.912133492923964 ;
	setAttr ".r" -type "double3" -6.9383527296033618 -37.000000000000661 -9.9562148234405475e-16 ;
createNode camera -s -n "perspShape" -p "persp";
	rename -uid "50B0D023-4B2C-04FA-6CFE-BA8D1A929E21";
	setAttr -k off ".v" no;
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 51.501588645538547;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
	setAttr ".ai_translator" -type "string" "perspective";
createNode transform -s -n "top";
	rename -uid "5F660FE3-486F-913A-4505-0BBBADE27A88";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 1000.1 0 ;
	setAttr ".r" -type "double3" -90 0 0 ;
createNode camera -s -n "topShape" -p "top";
	rename -uid "1EEC3923-4F8E-EA78-135F-A1BA9723AD0F";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -s -n "front";
	rename -uid "67B637BD-4046-6090-45B2-63904B8F3948";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 1000.1 ;
createNode camera -s -n "frontShape" -p "front";
	rename -uid "A2DB1DE2-4702-3B96-96A6-26A8BC7B0DC1";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -s -n "side";
	rename -uid "3BE04472-4B21-E3D4-30FD-7293176AE194";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 1000.1 0 0 ;
	setAttr ".r" -type "double3" 0 90 0 ;
createNode camera -s -n "sideShape" -p "side";
	rename -uid "081D325B-42C0-AC19-7784-B5BAA2D215C9";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode lightLinker -s -n "lightLinker1";
	rename -uid "DE09311C-4698-40EA-5F9F-BF9AA207806B";
	setAttr -s 20 ".lnk";
	setAttr -s 20 ".slnk";
createNode shapeEditorManager -n "shapeEditorManager";
	rename -uid "C1BBBE2E-4FA4-0952-DBF3-CAB8061C16D9";
createNode poseInterpolatorManager -n "poseInterpolatorManager";
	rename -uid "8AFCF3AC-42D9-6A95-382A-4E9174C8784B";
createNode displayLayerManager -n "layerManager";
	rename -uid "F2978554-4C61-9C08-FA0E-F382DC3757B4";
createNode displayLayer -n "defaultLayer";
	rename -uid "45985883-4069-EC0F-7CC6-1983C400CA72";
createNode renderLayerManager -n "renderLayerManager";
	rename -uid "527337E3-43A0-8F15-E2B1-2FAB7CC75697";
createNode renderLayer -n "defaultRenderLayer";
	rename -uid "B41E51DB-4162-C6EB-C2F2-FCA6C109E3D3";
	setAttr ".g" yes;
createNode reference -n "animRig_Lyette_GameReady_ModifiedRN";
	rename -uid "F331AC52-40EB-D8ED-53FB-DEB5635B6F23";
	setAttr ".fn[0]" -type "string" "D:/Projects/Games/COVID/COVID/SourceFiles/Characters/MainCharacter/Rig/animRig_Lyette_GameReady_Modified.ma";
	setAttr ".ed" -type "dataReferenceEdits" 
		"animRig_Lyette_GameReady_ModifiedRN"
		"animRig_Lyette_GameReady_ModifiedRN" 0
		"animRig_Lyette_GameReady_ModifiedRN" 2
		2 "animRig_Lyette_GameReady_Modified:file7" "fileTextureName" " -type \"string\" \"D:/Projects/Games/COVID/COVID/SourceFiles/Characters/MainCharacter/Textures/animRig_Lyette_Textures/animRig_Lyette_Textures/Lyette_lowpoly_Eye_BaseColor.png\""
		
		2 "animRig_Lyette_GameReady_Modified:file7" "colorSpace" " -type \"string\" \"sRGB\"";
	setAttr ".ptag" -type "string" "";
lockNode -l 1 ;
createNode ilrOptionsNode -s -n "TurtleRenderOptions";
	rename -uid "73033F59-4735-E66C-CFCB-7DB2EB3B34C0";
lockNode -l 1 ;
createNode ilrUIOptionsNode -s -n "TurtleUIOptions";
	rename -uid "2D865D2C-4285-464D-EA1F-EA929F42B174";
lockNode -l 1 ;
createNode ilrBakeLayerManager -s -n "TurtleBakeLayerManager";
	rename -uid "45B80D94-40CB-62F6-3F3B-C58823248DA6";
lockNode -l 1 ;
createNode ilrBakeLayer -s -n "TurtleDefaultBakeLayer";
	rename -uid "14A3CB7B-432C-6A24-ECB4-C9B01A241D71";
lockNode -l 1 ;
createNode script -n "sceneConfigurationScriptNode";
	rename -uid "0344C532-4D98-1461-E322-01BD43E7C7C7";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 250 -ast 1 -aet 250 ";
	setAttr ".st" 6;
createNode reference -n "sharedReferenceNode";
	rename -uid "B021E994-4445-EDFD-C758-BAAE2F467906";
	setAttr ".ed" -type "dataReferenceEdits" 
		"sharedReferenceNode";
createNode nodeGraphEditorInfo -n "hyperShadePrimaryNodeEditorSavedTabsInfo";
	rename -uid "C58032CB-46E3-C2B3-7FA9-8998942289AA";
	setAttr ".tgi[0].tn" -type "string" "Untitled_1";
	setAttr ".tgi[0].vl" -type "double2" -330.95236780151544 -323.80951094248991 ;
	setAttr ".tgi[0].vh" -type "double2" 317.85713022663526 338.09522466054096 ;
select -ne :time1;
	setAttr -av -k on ".cch";
	setAttr -av -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".o" 1;
	setAttr -av ".unw" 1;
	setAttr -k on ".etw";
	setAttr -k on ".tps";
	setAttr -av -k on ".tms";
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
select -ne :renderPartition;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 11 ".st";
	setAttr -cb on ".an";
	setAttr -cb on ".pt";
select -ne :renderGlobalsList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
select -ne :defaultShaderList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 12 ".s";
select -ne :postProcessList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 943 ".u";
select -ne :defaultRenderingList1;
	setAttr -s 2 ".r";
select -ne :defaultTextureList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 7 ".tx";
select -ne :initialShadingGroup;
	setAttr -av -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 10 ".dsm";
	setAttr -k on ".mwc";
	setAttr -cb on ".an";
	setAttr -cb on ".il";
	setAttr -cb on ".vo";
	setAttr -cb on ".eo";
	setAttr -cb on ".fo";
	setAttr -cb on ".epo";
	setAttr -k on ".ro" yes;
	setAttr -s 4 ".gn";
select -ne :initialParticleSE;
	setAttr -av -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".mwc";
	setAttr -cb on ".an";
	setAttr -cb on ".il";
	setAttr -cb on ".vo";
	setAttr -cb on ".eo";
	setAttr -cb on ".fo";
	setAttr -cb on ".epo";
	setAttr -k on ".ro" yes;
select -ne :defaultRenderGlobals;
	setAttr ".ren" -type "string" "arnold";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
select -ne :ikSystem;
	setAttr -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -k on ".nds";
	setAttr -k on ".bnm";
	setAttr -av -k on ".gsn";
	setAttr -k on ".gsv";
	setAttr -s 3 ".sol";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr "sharedReferenceNode.sr" "animRig_Lyette_GameReady_ModifiedRN.sr";
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
// End of Lyette_Walk.ma
